// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oneqcbxdfbqsmkbsqkwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uZXFjYnhkZmJxc21rYnNxa3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0OTg2NjUsImV4cCI6MjA2NzA3NDY2NX0.gHp8LDTL9hWNR8VA_3XuegQ0TGCHOnJxRl830UDC8n4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});